#pragma once

#include <trusty/tipc.h>
#define OEMCRYPTO_PORT "com.android.trusty.oemcrypto"
#define OEMCRYPTO_SECURE_PORT "com.android.trusty.oemcrypto.secure"
#define OEMCRYPTO_MAX_BUFFER_LENGTH 4096

enum oemcrypto_command : uint32_t{
    OEMCRYPTO_RESP_BIT = 1,
    OEMCRYPTO_STOP_BIT = 2,
    OEMCRYPTO_REQ_SHIFT = 2,
    OEMCRYPTO_CRYPTOENGINE_OPENSESSION = 0<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_DESTROYSESSION = 1<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_DERIVEKEYS = 2<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_RSADERIVEKEYS = 3<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_REFRESHKEY = 4<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_FINDSESSION = 5<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_NONCECOLLISION = 6<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_INSTALLKEYBOX = 7<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_USETESTKEYBOX = 8<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_DEVICEROOTKEY = 9<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_DEVICEROOTID = 10<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_TERMINATE = 11<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_VALIDATEKEYBOX = 12<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_GETOPENSESSIONNUM = 13<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_GETMAXNUMOFSESSION = 14<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_DEVICEROOTTOKENLEN = 15<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_NONCE_FLOOD_COUNT = 16<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_MAX_USAGETABLE_SIZE = 17<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_DESTINATION = 18<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_DEVICEROOTTOKEN = 19<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_CURRENT_HDCP_CAP = 20<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_INITIALIZE = 21<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_VALIDROOTOFTRUST = 22<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_LOADTESTRSAKEY = 23<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_USAGEABLE = 24<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_CREATEUSAGETABLEHEADER = 25<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_LOADUSAGETABLEHEADER = 26<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_SHRINKUSAGETABLEHEADER = 27<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_PREPANDSIGNLICENSEREQUEST = 28<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_PREPANDSIGNRENEWALREQUEST = 29<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_LOADLICENSE = 30<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_LOADRENEWAL = 31<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_SIGNPROVISIONINGREQUEST = 32<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_GENERIC_ENCRYPT = 33<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_GENERIC_DECRYPT = 34<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_GENERIC_SIGN = 35<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_GENERIC_VERIFY = 36<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_VALIDATAMESSGE = 37<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_LOARSAKEY = 38<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_INSTALLRSAENCRYPTEDKEY = 39<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_DECRYPTRSAKEY = 40<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_ENCRYPTRSAKEY = 41<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_QUERYKEYCONTROLBLOCK = 42<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_SELECTCONTENTKEY = 43<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_DEACTIVEUSAGEENTRY = 44<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_REPORTUSAGE = 45<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_LOADUSAGEENTRY = 46<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_SETNONCE = 47<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_CHECKNONCE = 48<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_CREATENEWUSAGEENTRY = 49<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_MOVEENTRY = 50<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_UPDATEUSAGEENTRY = 51<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_GENERATERSASIGNATURE = 52<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_GETNONCE = 53<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_RSASIGNATURESIZE = 54<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_LOADENTITLEDCONTENTKEYS = 55<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_LOADKEYS = 56<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_ODKPARSEPROVISIONING = 57<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_DECRYPTSAMPLE = 58<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_ALLOWEDSCHEMEMS = 59<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_MACKEYSERVER = 60<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_NONCEVALUE = 61<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_SUPPORTUSAGETABLE = 62<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_SETDECRYPTHASH = 63<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_GETHASHERRORCODE = 64<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_COPYBUFFER = 65<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_CRYPTOENGINE_SETTIME = 66<<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_ENABLE_SECURE_MODE = 67 <<OEMCRYPTO_REQ_SHIFT,
    OEMCRYPTO_DISABLE_SECURE_MODE = 68 <<OEMCRYPTO_REQ_SHIFT,
};
struct oemcrypto_message {
    int  cmd;
    uint32_t session_id;
    uint8_t payload[0];
};

const uint32_t TRUSTY_OEMCRYPTO_RECV_BUF_SIZE = 2 * PAGE_SIZE;
const uint32_t TRUSTY_OEMCRYPTO_SEND_BUF_SIZE =
        (PAGE_SIZE - sizeof(struct oemcrypto_message) - 16 /* tipc header */);

